version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: agrosense
      POSTGRES_PASSWORD: agrosense
      POSTGRES_DB: agrosense_db
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/