FROM ghcr.io/mlflow/mlflow:v3.4.0

COPY requirements/mlflow-requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN apt-get update && apt-get install -y curl

WORKDIR /mlflow

RUN chmod -R 777 /mlflow

EXPOSE 5000