FROM apache/airflow:2.7.3-python3.9

COPY requirements/airflow-requirements.txt /tmp/requirements.txt

COPY . /opt/airflow/agrosense

RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /opt/airflow
