FROM ghcr.io/mlflow/mlflow:v2.22.2

COPY requirements/mlflow-requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN apt-get update && apt-get install -y curl

WORKDIR /mlflow

EXPOSE 5000
