version: 2

models:
  - name: stg_weather
    description: "Staging model for weather sensor data from IoT API"
    columns:
      - name: id
        description: "Primary key for weather readings"
        data_type: number
        tests:
#          - unique
          - not_null

      - name: latitude
        description: "Latitude coordinate of weather sensor"
        data_type: number
        tests:
          - not_null

      - name: longitude
        description: "Longitude coordinate of weather sensor"
        data_type: number
        tests:
          - not_null

      - name: timestamp
        description: "Timestamp when weather data was recorded (converted from microseconds)"
        data_type: timestamp_ntz
        tests:
          - not_null

      - name: temperature
        description: "Air temperature in Celsius"
        data_type: number
        tests:
          - not_null

      - name: humidity
        description: "Relative humidity percentage (0-100)"
        data_type: number
        tests:
          - not_null

      - name: solar_radiation
        description: "Solar radiation in W/m²"
        data_type: number

      - name: pressure
        description: "Atmospheric pressure in hPa"
        data_type: number

      - name: created_at
        description: "Timestamp when record was created in database (converted from microseconds)"
        data_type: timestamp_ntz
        tests:
          - not_null

  - name: stg_soil
    description: "Staging model for soil sensor data from IoT API"
    columns:
      - name: id
        description: "Primary key for soil readings"
        data_type: number
        tests:
#          - unique
          - not_null

      - name: timestamp
        description: "Timestamp when soil data was recorded (converted from microseconds)"
        data_type: timestamp_ntz
        tests:
          - not_null

      - name: t_0_cm
        description: "Soil temperature at surface (0cm depth) in Celsius"
        data_type: number
        tests:
          - not_null

      - name: t_10_cm
        description: "Soil temperature at 10cm depth in Celsius"
        data_type: number
        tests:
          - not_null

      - name: moisture
        description: "Soil moisture content percentage"
        data_type: number
        tests:
          - not_null

      - name: ph_0_5cm
        description: "Soil pH level at 0-5cm depth"
        data_type: number
        tests:
          - not_null

      - name: ph_5_15cm
        description: "Soil pH level at 5-15cm depth"
        data_type: number

      - name: ph_15_30cm
        description: "Soil pH level at 15-30cm depth"
        data_type: number

      - name: ph_30_60cm
        description: "Soil pH level at 30-60cm depth"
        data_type: number

      - name: ph_60_100cm
        description: "Soil pH level at 60-100cm depth"
        data_type: number

      - name: ph_100_200cm
        description: "Soil pH level at 100-200cm depth"
        data_type: number

      - name: created_at
        description: "Timestamp when record was created in database (converted from microseconds)"
        data_type: timestamp_ntz
        tests:
          - not_null

  - name: stg_crop_yield
    description: "Staging model for historical crop yield dataset (Kaggle source)"
    columns:
      - name: area
        description: "Country or region name"
        data_type: varchar
        tests:
          - not_null

      - name: item
        description: "Crop type (e.g., Wheat, Rice, Maize)"
        data_type: varchar
        tests:
          - not_null

      - name: year
        description: "Year of observation"
        data_type: number
        tests:
          - not_null

      - name: hg_ha_yield
        description: "Crop yield in hectograms per hectare"
        data_type: number
        tests:
          - not_null

      - name: average_rainfall_mm_per_year
        description: "Average annual rainfall in millimeters"
        data_type: number
        tests:
          - not_null

      - name: pesticides_tonnes
        description: "Total pesticide use in tonnes"
        data_type: number

      - name: avg_temp
        description: "Average temperature in degrees Celsius"
        data_type: number