version: 2

models:
  - name: my_first_dbt_model
    description: "My first dbt model"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name field"
      - name: created_at
        description: "Timestamp of creation"

  - name: my_second_dbt_model
    description: "Model that references the first model"
    columns:
      - name: id
        description: "ID from first model"
      - name: status
        description: "Processing status"
        tests:
          - accepted_values:
              values: ['processed', 'pending', 'failed']